version: "3.8"
services:
  llm_agent:
    build:
      context: .
      dockerfile: llm_agent/dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        GRAFANA_WEB_HOOK: ${GRAFANA_WEB_HOOK}
        LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
        LANGCHAIN_PROJECT: ${LANGCHAIN_PROJECT}
        WEBEX_ROOM_ID: ${WEBEX_ROOM_ID}
        WEBEX_TEAMS_ACCESS_TOKEN: ${WEBEX_TEAMS_ACCESS_TOKEN}
        WEBEX_APPROVED_USERS_MAIL: ${WEBEX_APPROVED_USERS_MAIL}
    image: python:3.12.2
    container_name: llm_agent
    ports:
      - "5001:5001"

  grafana:
    build:
      context: .
      dockerfile: grafana/dockerfile
      args:
        LLM_HTTP_PORT: ${LLM_HTTP_PORT}
        GRAFANA_TOKEN: ${GRAFANA_TOKEN}
        WEBEX_ROOM_ID: ${WEBEX_ROOM_ID}
        GRAFANA_VERSION: ${GRAFANA_VERSION}
        GRAFANA_WEB_HOOK: ${GRAFANA_WEB_HOOK}
        WEBEX_TEAMS_ACCESS_TOKEN: ${WEBEX_TEAMS_ACCESS_TOKEN}
    image: grafana:${GRAFANA_VERSION}
    container_name: grafana
    ports:
      - "3000:3000"

  influxdb:
    build:
      context: .
      dockerfile: influxdb/dockerfile
      args:
        INFLUXDB_VERSION: ${INFLUXDB_VERSION}
        DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_MODE}
        DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
        DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
        DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
        DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    image: influxdb:${INFLUXDB_VERSION}
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb2

  telegraf:
    build:
      context: .
      dockerfile: telegraf/dockerfile
      args:
        TELEGRAF_VERSION: ${TELEGRAF_VERSION}
        TELEGRAF_ORG: ${TELEGRAF_ORG}
        TELEGRAF_TOKEN: ${TELEGRAF_TOKEN}
        TELEGRAF_BUCKET: ${TELEGRAF_BUCKET}
    image: telegraf:${TELEGRAF_VERSION}
    container_name: telegraf
    ports:
      - "57500:57500"

volumes:
  influxdb:
