apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: telemtry-org
      defaultBucket: mdt_grpc
      tlsSkipVerify: true
    secureJsonData:
      token: $GRAFANA_TOKEN
